### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by fangq** [ubjson/universal-binary-json#107]
please check, http://ubjson.org is currently unreachable

**Comment by rkalla** [comment]
Looking into it - host doesn't provide sufficient tooling to make this
easy...

**Comment by kag0** [comment]
Is the website all static content? Could switch over to github pages if so.

**Comment by kag0** [comment]
Is this project still active or has it been pretty well abandoned?

**Comment by fangq** [comment]
I am also happy to help. UBJSON is my preferred binary format in a new research project called OpenJData: http://openjdata.org. I am happy to step in and push this project forward, or alternatively, make a derived specification - there are a couple of minor things that I would like to add and formalize, including the [optimized ND-array header](https://github.com/fangq/jdata/blob/master/JData_specification.md#binary-jdata-storage-grammar), and the missing uint{16,32,64} types.

CBOR and MessagePack have bigger communities, but the non-ascii markers makes it entirely non-human-readable. in comparison, UBJSON's quasi-human-readability is a big strength.

I have web hosting space, happy to share. But regarding the completion of the specification, I think the MarkDown version of the specification made by Iotic Labs Ltd is the better way to co-develop this specification

https://github.com/Iotic-Labs/py-ubjson/blob/dev-contrib/UBJSON-Specification.md

**Comment by rkalla** [comment]
I'm working with GoDaddy on recovering it.

**Comment by rkalla** [comment]
Site is back up - no idea what happened.

@Qianqian if you'd like to participate more officially in the spec, let's
discuss - rkalla@gmail.com

Best wishes,
Riyad
