### ISSUE TITLE
List of companies using UBJSON

### ISSUE THREAD

**Issue by jviotti** [ubjson/universal-binary-json#111]
Hey there! I'm interested in compiling a (small) list of companies using UBJSON in production for research purposes, and Google is not helping much. Are you aware of a bunch companies using the format?

**Comment by AnyCPU** [comment]
@rkalla Do you? ^^^

**Comment by rkalla** [comment]
Sorry, I don't off hand

**Comment by jviotti** [comment]
No worries, thanks lot!
