### ISSUE TITLE
Why can't typed containers be nested?

### ISSUE THREAD

**Issue by tbuitenhuis** [ubjson/universal-binary-json#73]
I know typing will probably change in the next version, so this will be a moot point, but I’m still curious what I’m missing. It seems to me that something like

```
[ [ ][$][ [ ][#][U][2]
[$][i][#][U][3][1][2][3]
[$][i][#][U][3][4][5][6]
```

(that’s `[ [1, 2, 3], [4, 5, 6] ]` )

is unambiguous and I can’t think of an ambiguous counterexample.

**Comment by Steve132** [comment]
I'm pretty sure that typed containers *can* be nested.  That was the final resolution of this thread https://github.com/thebuzzmedia/universal-binary-json/issues/43

It resolved the "STCs must not contain other STCs" issue and said that what you just typed would in fact be valid.  

In fact, UBJ (my C language parser) handles your case already.

Here is the relevant part of the spec: http://ubjson.org/type-reference/container-types/#optimized-format

> yes it is possible for an array or object to define their type as ‘[‘ or ‘{‘ to signal that they themselves contain additional containers!

**Comment by tbuitenhuis** [comment]
Then this rule in the spec needs to be clarified:

> A container that specifies a type must not contain any additional type markers for any contained value.

It can be interpreted as “A container can have a ‘array’ or ‘object’ as its type, but those inner arrays or objects must not have types themselves”. If that’s not what it means, I actually have no idea what it does mean. Maybe that line should just be removed.

**Comment by Steve132** [comment]
> If that’s not what it means, I actually have no idea what it does mean. Maybe that line should just be removed.

It seems straightforward and means exactly what it says.  It says that no type markers are inside the container for direct children, because the type is known (and must be constant) across the whole container type.
