### ISSUE TITLE
Language for Endianness for storing float32 and float64 is not clear

### ISSUE THREAD

**Issue by fangq** [ubjson/universal-binary-json#79]
Two places have mentioned the endianness issues:

http://ubjson.org/type-reference/value-types/#numeric-byte-order-endianness

and

http://ubjson.org/#endian

the first link specifies explicitly that all integer types are stored in the Big-Endian format. However, for floats, the only language was "IEEE 754 compliant". However, AFAIK, IEEE 754 does not specify Endianness.

The second link does mention that all "numeral types" are stored in "Big Endian" format. However, it is very brief and nonspecific.

If the spec means to say that float32 and float64 should also be stored in the Big-Endian format, please say so explicitly in the "Byte Order / Endianness" section of the "[type-reference](http://ubjson.org/type-reference/value-types/#numeric-byte-order-endianness)" page.

Please clarify. thanks

**Comment by Steve132** [comment]
I agree this is a problem with the current spec.   I implemented it as big-endian.
