### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Frizlab** [ubjson/universal-binary-json#87]
I’m considering writing a parser for a language which is not already in the registered list of parsers. Is it worth my time? Latest commit in the specs is a year ago, which is not that old, but starts to date a little bit.

I found this repo (https://github.com/ubjson/universal-binary-json-java), which I guess is the official (or at least the first?) implementation of the specs, but latest commit dates from three years ago! Which is old. Definitely.
@Pyrolistical: As the only committer of the repo above, do you have any insights? Also, you have some stuff called compact arrays (when size of the array is less than 256), is this something that still exists?

Thank you all in advance!

**Comment by AnyCPU** [comment]
No commits do not mean that it is dead. If you have suggestions how to spread the spec, please share them with us.

**Comment by Pyrolistical** [comment]
All I did was add a gradle build for that other repo. Funnily enough I don't do Java anymore, so this project is more interesting to me!

**Comment by Frizlab** [comment]
@AnyCPU Sadly I don’t, but I do appreciate the initiative and the format in general; I’ll try and recommend people to use it around me 🙂
