### ISSUE TITLE
No-op Questions

### ISSUE THREAD

**Issue by Frizlab** [ubjson/universal-binary-json#88]
I have two very specific questions regarding No-op. I have read #80, but I did not find a definitive answer there, so I'm trying a new thread and hoping for the best 🙂

In the specs, there is an example of an “optimised” array strongly typed No-op: `[[][$][N][#][I][512]`. My question is: what does parsing this should return? My guess is: an empty array.

Now let’s get creative, and create an _object_ strongly typed No-op: `[{][$][N][#][i][1][i][4][name]`. My question is the same: what does parsing this should return? My guess is the same: an empty dictionary!

Please note, I’m expecting definitive answers, not guesses. If you don’t know the answer, or are not certain, simply upvote the question, or do nothing.

Thank you!

**Comment by AnyCPU** [comment]
The 'N' is just placeholder. I think it should be skipped while parsing.

**Comment by Frizlab** [comment]
@AnyCPU Yes but in the case of a **strongly typed** array or an object, where `N` is the type of the array or object, what does that mean, skipping it? I cannot skip the type of the array or object, that wouldn’t mean anything!

The spec could impose strongly typed arrays or objects not to be typed `N`, but I don’t think it currently does (and if it did, there would be an invalid example in the specs).

For me, in its current state the spec is simply invalid and cannot be implemented because of this case. I can do a pull request making the necessary changes if you want 🙂

**Comment by AnyCPU** [comment]
@Frizlab I appreciate your work 
@rkalla please review an upcoming PR

**Comment by Frizlab** [comment]
No-op case solved with #89, closing this issue.
