### ISSUE TITLE
Is ubjson@thebuzzmedia.com Still a Valid Contact Email?

### ISSUE THREAD

**Issue by Frizlab** [ubjson/universal-binary-json#90]
The current website at thebuzzmedia.com makes one wonder…

**Comment by AnyCPU** [comment]
@rkalla ping

**Comment by rkalla** [comment]
Sorry guys - that email address is no longer valid, I thought I had updated the documentation to point directly at me (rkalla@gmail.com) but to Friz's original question, I am no longer maintaining this full time.

**Comment by Frizlab** [comment]
No problem. I’m closing this issue in favour of its pull request (#91).
