### ISSUE TITLE
Is the spec stable?

### ISSUE THREAD

**Issue by shelacek** [ubjson/universal-binary-json#94]
Hello,
I was looking for some binary alternative to *JSON* and I have to admit that *UBJSON* is the best of the variants - simple, effective and allows to transfer a binary blob as it is (`uint8` STC). But is the specification at least partly stable? There are some ongoing issues/proposals, which have potential completely break compatibility and there are no progress with these recently (according GitHub). Is there any plan or timescale to freeze the spec?

Thanks.

**Comment by rkalla** [comment]
There are not plans to break the spec at this point.

**Comment by shelacek** [comment]
Thanks @rkalla, it's enough for me.
