### ISSUE TITLE
Contact form not working?

### ISSUE THREAD

**Issue by shelacek** [ubjson/universal-binary-json#95]
Hello,
I was under suspicion, that contact form on http://ubjson.org/contact/ is not working. Nothing will happen on submit. Responses are the same on GET/POST.

**Comment by AnyCPU** [comment]
@rkalla hi) please take a look at this

**Comment by rkalla** [comment]
"Fixed"! (by killing the contact form)

**Comment by shelacek** [comment]
Yaeh, this is probably the most appropriate solution :-). Thanks.
